from enum import Enum
from uuid import UUID
from sqlalchemy import ForeignKey, String, Text, Enum as SQLEnum
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship
from .base import Base, UUIDPKMixin, TimestampMixin


class AgentRunStatus(str, Enum):
    pending = "pending"
    running = "running"
    completed = "completed"
    failed = "failed"
    aborted = "cancelled"


class AgentRun(Base, UUIDPKMixin, TimestampMixin):
    """An autonomous multi-agent workflow session."""
    __tablename__ = "agent_runs"

    user_id: Mapped[UUID] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), nullable=False)
    conversation_id: Mapped[UUID | None] = mapped_column(ForeignKey("conversations.id", ondelete="SET NULL"), nullable=True)
    
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    goal: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[AgentRunStatus] = mapped_column(
        SQLEnum(AgentRunStatus), default=AgentRunStatus.pending, nullable=False
    )
    
    # Configuration/State
    plan: Mapped[dict | None] = mapped_column(JSONB, comment="The high-level strategy generated by the Planner.")
    metadata_json: Mapped[dict | None] = mapped_column(JSONB, name="metadata")
    
    # Relationships
    tasks: Mapped[list["AgentTask"]] = relationship(back_populates="run", cascade="all, delete-orphan")

    __table_args__ = (
        {"comment": "Orchestrated autonomous workflows."}
    )
