"""add_agent_run_schemas

Revision ID: 39b10c768130
Revises: a1b2c3d4e5f6
Create Date: 2026-04-27 20:33:31.249748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39b10c768130'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'aborted', name='agentrunstatus'), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='The high-level strategy generated by the Planner.'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUIDv4).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation time (UTC).'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification time (UTC).'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_runs_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs')),
    comment='Orchestrated autonomous workflows.'
    )
    op.create_table('agent_tasks',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_role', sa.String(length=50), nullable=False, comment='planner, worker, or critic'),
    sa.Column('model_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'skipped', name='taskstatus'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUIDv4).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation time (UTC).'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification time (UTC).'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_tasks_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_tasks')),
    comment='Individual steps or tool-calls within an autonomous run.'
    )
    op.alter_column('context_entries', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment="Top-level category, e.g. 'Brand', 'Market', 'Product'.",
               existing_comment='Top-level category.',
               existing_nullable=True)
    op.alter_column('context_entries', 'subcategory',
               existing_type=sa.VARCHAR(length=100),
               comment="Sub-category, e.g. 'Voice', 'Audience'.",
               existing_comment='Sub-category.',
               existing_nullable=True)
    op.alter_column('context_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('context_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last modification time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'source_type',
               existing_type=sa.VARCHAR(length=16),
               comment="'manual' = uploaded via Neural Archive UI; 'chat' = auto-saved from chat attachment.",
               existing_comment="'manual' = Neural Archive UI; 'chat' = auto-saved from chat attachment.",
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('messages', 'model',
               existing_type=sa.VARCHAR(length=200),
               comment='Model that generated this message (assistant only). Tracks per-message model rotation.',
               existing_comment='Model that generated this message.',
               existing_nullable=True)
    op.alter_column('model_capability_overrides', 'persona',
               existing_type=sa.VARCHAR(length=20),
               comment='Persona category: drizzle (chat/tools), nimbus (generative), or storm (orchestrator).',
               existing_comment='Persona: drizzle, nimbus, or storm.',
               existing_nullable=False,
               existing_server_default=sa.text("'drizzle'::character varying"))
    op.alter_column('model_capability_overrides', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Task-type tags: default, vision, coding, math, creative_writing, etc. Used for model rotation.',
               existing_comment='Task-type tags used for model rotation.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('model_capability_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_capability_overrides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last modification time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'model_capability_overrides',
        existing_comment='User-defined capability tags for models (primarily Ollama local models).',
        schema=None
    )
    op.alter_column('prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Row creation time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last modification time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_prompts_is_default'), table_name='prompts')
    op.drop_table_comment(
        'prompts',
        existing_comment='Saved system prompt templates.',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'prompts',
        'Saved system prompt templates.',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_prompts_is_default'), 'prompts', ['is_default'], unique=False)
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'model_capability_overrides',
        'User-defined capability tags for models (primarily Ollama local models).',
        existing_comment=None,
        schema=None
    )
    op.alter_column('model_capability_overrides', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_capability_overrides', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_capability_overrides', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Task-type tags used for model rotation.',
               existing_comment='Task-type tags: default, vision, coding, math, creative_writing, etc. Used for model rotation.',
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('model_capability_overrides', 'persona',
               existing_type=sa.VARCHAR(length=20),
               comment='Persona: drizzle, nimbus, or storm.',
               existing_comment='Persona category: drizzle (chat/tools), nimbus (generative), or storm (orchestrator).',
               existing_nullable=False,
               existing_server_default=sa.text("'drizzle'::character varying"))
    op.alter_column('messages', 'model',
               existing_type=sa.VARCHAR(length=200),
               comment='Model that generated this message.',
               existing_comment='Model that generated this message (assistant only). Tracks per-message model rotation.',
               existing_nullable=True)
    op.alter_column('documents', 'source_type',
               existing_type=sa.VARCHAR(length=16),
               comment="'manual' = Neural Archive UI; 'chat' = auto-saved from chat attachment.",
               existing_comment="'manual' = uploaded via Neural Archive UI; 'chat' = auto-saved from chat attachment.",
               existing_nullable=False,
               existing_server_default=sa.text("'manual'::character varying"))
    op.alter_column('context_entries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last modification time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('context_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Row creation time (UTC).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('context_entries', 'subcategory',
               existing_type=sa.VARCHAR(length=100),
               comment='Sub-category.',
               existing_comment="Sub-category, e.g. 'Voice', 'Audience'.",
               existing_nullable=True)
    op.alter_column('context_entries', 'category',
               existing_type=sa.VARCHAR(length=100),
               comment='Top-level category.',
               existing_comment="Top-level category, e.g. 'Brand', 'Market', 'Product'.",
               existing_nullable=True)
    op.drop_table('agent_tasks')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
