"""session_skills_config

Revision ID: b1d26d39f399
Revises: 3d8803d16ffc
Create Date: 2026-04-24 01:47:04.305813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1d26d39f399'
down_revision: Union[str, Sequence[str], None] = '3d8803d16ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Owner user.'),
    sa.Column('custom_system_prompt', sa.Text(), nullable=True, comment="Global instructions like 'Always be concise'."),
    sa.Column('user_context', sa.Text(), nullable=True, comment="Facts about the user like 'I prefer Next.js'."),
    sa.Column('api_keys', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True, comment='Encrypted/raw API keys for hosted providers.'),
    sa.Column('id', sa.Uuid(), nullable=False, comment='Primary key (UUIDv4).'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Row creation time (UTC).'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last modification time (UTC).'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id')),
    comment='User-defined agent instructions and preferences.'
    )
    op.add_column('conversations', sa.Column('auto_skills', sa.Boolean(), server_default='true', nullable=False, comment='If true, AI chooses skills automatically.'))
    op.add_column('conversations', sa.Column('enabled_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False, comment='List of skill names/IDs enabled manually when auto_skills is false.'))
    op.create_table_comment(
        'conversations',
        'User chat sessions. Soft-deleted via deleted_at.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'documents',
        'User-uploaded documents. Raw files in MinIO, vectors in Qdrant.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'messages',
        'Individual messages within a conversation.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'skill_executions',
        'Audit trail of skill executions within conversations.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'skills',
        'Installed skills. Manifest stored as JSONB, validated on insert.',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'users',
        'System users. Primary identity for data ownership.',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'users',
        existing_comment='System users. Primary identity for data ownership.',
        schema=None
    )
    op.drop_table_comment(
        'skills',
        existing_comment='Installed skills. Manifest stored as JSONB, validated on insert.',
        schema=None
    )
    op.drop_table_comment(
        'skill_executions',
        existing_comment='Audit trail of skill executions within conversations.',
        schema=None
    )
    op.drop_table_comment(
        'messages',
        existing_comment='Individual messages within a conversation.',
        schema=None
    )
    op.drop_table_comment(
        'documents',
        existing_comment='User-uploaded documents. Raw files in MinIO, vectors in Qdrant.',
        schema=None
    )
    op.drop_table_comment(
        'conversations',
        existing_comment='User chat sessions. Soft-deleted via deleted_at.',
        schema=None
    )
    op.drop_column('conversations', 'enabled_skills')
    op.drop_column('conversations', 'auto_skills')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
